---
# file: tasks/install-node-exporter.yml
#
# Install Prometheus node-exporter.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#

- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_pushgateway_tarball_url: "https://github.com/prometheus/pushgateway/releases/download/{{ prometheus_pushgateway_version }}/pushgateway-{{ prometheus_pushgateway_version }}.linux-amd64.tar.gz"
        prometheus_pushgateway_subdir: "{{ prometheus_install_path }}/pushgateway-{{ prometheus_pushgateway_version }}.linux-amd64"
      when: ansible_userspace_bits == "64"

    - name: set internal variables for convenience
      set_fact:
        prometheus_pushgateway_tarball_url: "https://github.com/prometheus/pushgateway/releases/download/{{ prometheus_pushgateway_version }}/pushgateway-{{ prometheus_pushgateway_version }}.linux-386.tar.gz"
        prometheus_pushgateway_subdir: "{{ prometheus_install_path }}/pushgateway-{{ prometheus_pushgateway_version }}.linux-386"
      when: ansible_userspace_bits == "32"

    - name: create pushgateway directory
      file: path="{{ prometheus_pushgateway_subdir }}" state=directory

    - name: set daemon dir for >= 0.12
      set_fact:
        prometheus_pushgateway_daemon_dir: "{{ prometheus_pushgateway_subdir }}"
      when: prometheus_version | version_compare('0.12', '>=')

    - name: set daemon dir for < 0.12
      set_fact:
        prometheus_pushgateway_daemon_dir: "{{ prometheus_install_path }}"
      when: prometheus_version | version_compare('0.12', '<')

    - name: download and untar pushgateway tarball
      unarchive:
        src: "{{ prometheus_pushgateway_tarball_url }}"
        dest: "{{ prometheus_pushgateway_subdir }}"
        copy: no

  when: prometheus_pushgateway_version != "git"


- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_pushgateway_git_url: "https://github.com/prometheus/pushgateway.git"
        prometheus_pushgateway_src_path: "{{ prometheus_goroot }}/src/github.com/prometheus/pushgateway"
        prometheus_pushgateway_daemon_dir: "{{ prometheus_install_path }}"

    - name: delete the pushgateway build directory, if necessary
      file: path={{ prometheus_pushgateway_src_path }}  state=absent
      when: prometheus_rebuild

    - name: mkdir for pushgateway source code
      file: path={{ prometheus_pushgateway_src_path }}  state=directory

    - name: clone the pushgateway project src
      git:
        repo: "{{ prometheus_pushgateway_git_url }}"
        dest: "{{ prometheus_pushgateway_src_path }}"
        force: yes

    - name: build pushgateway source code
      command: make
      args:
        chdir: "{{ prometheus_pushgateway_src_path }}"
        creates: pushgateway
      environment:
        GO15VENDOREXPERIMENT: 1
        GOROOT: "{{ prometheus_goroot }}"
        GOPATH: "{{ prometheus_gopath }}"
        PATH: "{{ ansible_env.PATH }}:{{ prometheus_goroot }}/bin:{{ prometheus_gopath }}/bin"

    - name: copy the built pushgateway to the install path
      command: "cp {{ prometheus_pushgateway_src_path }}/pushgateway {{ prometheus_install_path }}"
      args:
        creates: "{{ prometheus_install_path }}/pushgateway"

  when: prometheus_pushgateway_version == "git"



- name: set permissions, owner and group
  file: path={{ prometheus_pushgateway_daemon_dir }}/pushgateway owner={{ prometheus_user }} group={{ prometheus_group }} mode="go-w"

- name: set pushgateway variables
  copy: src="../files/etc-default-pushgateway"  dest=/etc/default/pushgateway

- name: copy INIT script to server
  template: src="../templates/pushgateway.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/pushgateway"  mode="a+x"
  when: not prometheus_node_exporter_use_systemd|bool

- name: copy systemd config to server
  template: src="../templates/pushgateway.service.j2"  dest="/lib/systemd/system/pushgateway.service"
  when: prometheus_node_exporter_use_systemd


- name: set INIT status and start
  service: name=pushgateway enabled=yes state=started
